# Generated by Django 5.1.6 on 2025-02-15 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0003_images_tags'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categories',
            new_name='Brand',
        ),
        migrations.RenameModel(
            old_name='Brands',
            new_name='Categorie',
        ),
        migrations.RenameModel(
            old_name='Colors',
            new_name='Color',
        ),
    ]
