# Generated by Django 5.1.6 on 2025-02-15 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0004_rename_categories_brand_rename_brands_categorie_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categorie',
            new_name='Brands',
        ),
        migrations.RenameModel(
            old_name='Brand',
            new_name='Categories',
        ),
        migrations.RenameModel(
            old_name='Color',
            new_name='Colors',
        ),
    ]
