# Generated by Django 5.1.6 on 2025-02-15 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0005_rename_categorie_brands_rename_brand_categories_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categories',
            new_name='Brand',
        ),
        migrations.RenameModel(
            old_name='Brands',
            new_name='Categorie',
        ),
        migrations.RenameModel(
            old_name='Colors',
            new_name='Color',
        ),
        migrations.RemoveField(
            model_name='product',
            name='categories',
        ),
        migrations.AddField(
            model_name='product',
            name='categorie',
            field=models.ForeignKey(default=200, on_delete=django.db.models.deletion.CASCADE, to='store_app.categorie'),
            preserve_default=False,
        ),
    ]
