# Generated by Django 5.1.6 on 2025-02-15 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0006_rename_categories_brand_rename_brands_categorie_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='categorie',
            new_name='categories',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Filter_Price',
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_app.brand'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(choices=[('IN STOCK', 'IN STOCK'), ('OUT OF STOCK', 'OUT OF STOCK')], max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='filter_price',
            field=models.ForeignKey(default=200, on_delete=django.db.models.deletion.CASCADE, to='store_app.filter_price'),
            preserve_default=False,
        ),
    ]
