# Generated by Django 5.1.6 on 2025-02-23 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0008_alter_product_stock'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tags',
            new_name='Tag',
        ),
    ]
