# Generated by Django 5.1.6 on 2025-02-23 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0009_rename_tags_tag'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Images',
            new_name='Image',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='image',
            new_name='images',
        ),
    ]
