# Generated by Django 5.1.6 on 2025-02-23 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0010_rename_images_image_rename_image_product_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='Product_image/img'),
        ),
    ]
