# Generated by Django 5.1.6 on 2025-02-23 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0011_alter_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='images',
            field=models.ImageField(upload_to='Product_image/img'),
        ),
    ]
