# Generated by Django 5.1.6 on 2025-02-23 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0013_alter_image_image_alter_product_images'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='Images',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='images',
            new_name='image',
        ),
    ]
