# Generated by Django 5.1.6 on 2025-02-23 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0016_contact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='Contact_us',
        ),
    ]
