# Generated by Django 5.1.6 on 2025-04-03 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0019_order_paid_order_payment_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='additional_info',
        ),
    ]
