# Generated by Django 5.1.6 on 2025-04-05 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0020_remove_order_additional_info'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='contry',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='psotcode',
            new_name='postcode',
        ),
    ]
